### PR TITLE
Adding a command line tool for publishing feature files

### PR DESCRIPTION
**Pull request by jmezach**
I've added a command line tool for publishing feature files to Augurk. It does not support publishing test results (yet).

### CODE REVIEW

**Comment by marktaling** [comment]
As discussed, great contribution. Merged it.

**Comment by jmezach** [comment]
I see that the build task for TFS 2015 has also been merged. Note that it currently requires the command line tool to be present inside a tool sub folder hen you upload the task to TFS for it to work.

I'm still figuring out what the best way would be to handle this. I see two options:

1. Let the build task depend on a package that has to be installed in the solution. This has the benefit of not needing the tool itself packaged with the task, but if you use the task with a solution that doesn't have the package installed the build will fail.
2. Include the tool with the task itself. This way it only has to be downloaded to the agent once for each version of the task you publish to your TFS server. Unfortunately if you upload many different versions of it you will have a lot of duplicate data in your TFS server.

Suggestions?

**Comment by marktaling** [comment]
Couldn't we go for option 1 without the build failing?
You can include the package in you solutions, for the solutions you wish to publish.
On the build you configure the task to publish, if the solution has the package. That way you get control on both ends:
On the solution level you can either include it or not. And on the build the same goes by either configuring the task, or not...

**Comment by jmezach** [comment]
That would probably work. But I think you'll want to know if the feature files aren't published, especially if you were publishing them for a particular solution and someone uninstalled the required package later on. In that case you'll have no way of knowing whether your feature files are still being published. Perhaps we should issue a warning if you've included the task in your build definition but do not have the necessary package installed?

**Comment by marktaling** [comment]
The warning would be nice. Would it be an option to have an additional checkbox on the task to upgrade such warnings to errors? (And as such breaking the build?)
In that case we would cover both scenarios.

**Comment by jmezach** [comment]
Sure, that shouldn't be too hard to do ;).

**Pull request merged**
